language: objective-c
env:
  global: 
    - secure: "nq3wz55Nra0jAS2L4Kl47Ybxa+CQWtMdwxzSXvBs9hnW3d9DNSf9rZRbMsOD\n1xM8HSU5tck9H9hxTN1quOpug4cvU7p5cx9NKw6GNOV1MxScQs42oAlDcTp3\nEnbi31eAGMA3gLckgNcCyOvr8rYuBsXPlVCNN6pkxfHi0a5mouw="
    - secure: "Y40/B6H0S3kj+o+RqgTX8BA3utf0TSY+ryAY/N7X8cJ7pJ8d4SGRaD304iDa\n8tEv79hHWMwgFnQnr1h0/9CfAcOZ0Rg/S3YioW9AYnkw/Ta7K4wlKTtxdl75\nw7RqgcTE9vayFegy2NRNsgVURPO9hlDgeuantCAXIbhQ873taKE="
    - "OSX_VERSION=macosx10.8"
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=travis-artifacts"
    
before_install: bundle install
script: bundle exec rake ci:travis
after_script:
  - "bundle exec travis-artifacts upload --path ci_artifacts/ --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"
